import type { Genre, Mood, Influence, ChordVoicing, Tempo } from "./types";

export const GENRES: Genre[] = [
  {
    id: "math-rock",
    label: "Math Rock",
    icon: "◇",
    description: "Tapping, odd meters, interlocking guitars",
    color: "#E8453C",
    subgenres: ["midwest emo", "post-rock", "twinkle"],
  },
  {
    id: "shoegaze",
    label: "Shoegaze",
    icon: "◎",
    description: "Wall of sound, heavy reverb, buried vocals",
    color: "#8B5CF6",
    subgenres: ["noise pop", "dream noise", "ethereal"],
  },
  {
    id: "dreampop",
    label: "Dreampop",
    icon: "◌",
    description: "Ethereal, lush pads, airy vocals",
    color: "#06B6D4",
    subgenres: ["ethereal wave", "ambient pop", "chillwave"],
  },
  {
    id: "lofi",
    label: "Lo-Fi",
    icon: "◈",
    description: "Tape warmth, vinyl crackle, mellow keys",
    color: "#F59E0B",
    subgenres: ["lo-fi hip hop", "chillhop", "study beats"],
  },
  {
    id: "post-punk",
    label: "Post-Punk",
    icon: "▣",
    description: "Angular guitars, driving bass, cold atmosphere",
    color: "#6B7280",
    subgenres: ["darkwave", "cold wave", "gothic rock"],
  },
  {
    id: "bedroom-pop",
    label: "Bedroom Pop",
    icon: "♡",
    description: "Intimate, slightly detuned, confessional",
    color: "#EC4899",
    subgenres: ["indie pop", "DIY pop", "soft indie"],
  },
  {
    id: "prog-house",
    label: "Progressive House",
    icon: "△",
    description: "Building layers, trance pads, euphoric drops",
    color: "#10B981",
    subgenres: ["melodic house", "progressive trance", "deep house"],
  },
  {
    id: "nu-metal",
    label: "Nu-Metal",
    icon: "⬡",
    description: "Downtuned riffs, aggressive, dynamic shifts",
    color: "#64748B",
    subgenres: ["alt-metal", "rap-metal", "heavy alternative"],
  },
  {
    id: "j-rock",
    label: "J-Rock",
    icon: "⊕",
    description: "Melodic Japanese rock, visual kei influence, dramatic dynamics",
    color: "#FF6B35",
    subgenres: ["visual kei", "Japanese alternative", "anime rock"],
  },
  {
    id: "ambient",
    label: "Ambient",
    icon: "∞",
    description: "Textural soundscapes, evolving pads, no rhythm",
    color: "#3B82F6",
    subgenres: ["dark ambient", "drone", "ambient electronic"],
  },
  {
    id: "indie-folk",
    label: "Indie Folk",
    icon: "⌘",
    description: "Acoustic fingerpicking, warm harmonies, organic",
    color: "#92400E",
    subgenres: ["chamber folk", "freak folk", "neofolk"],
  },
  {
    id: "hyperpop",
    label: "Hyperpop",
    icon: "✦",
    description: "Maximalist, pitch-shifted, glitchy, chaotic energy",
    color: "#D946EF",
    subgenres: ["glitchcore", "digicore", "bubblegum bass"],
  },
];

export const MOODS: Mood[] = [
  { id: "melancholy", label: "Melancholy", textures: "tape hiss, reverb wash, detuned chorus", intensity: 2 },
  { id: "euphoric", label: "Euphoric", textures: "shimmering delays, bright harmonics, ascending arpeggios", intensity: 4 },
  { id: "focused", label: "Focused / Study", textures: "steady pulse, warm compression, gentle sidechain", intensity: 2 },
  { id: "nostalgic", label: "Nostalgic", textures: "analog warmth, room mic bleed, vinyl saturation", intensity: 2 },
  { id: "anxious", label: "Anxious / Tense", textures: "dissonant clusters, tremolo picking, unstable pitch", intensity: 4 },
  { id: "dreamy", label: "Dreamy / Floating", textures: "infinite reverb, pitch-shifted pads, soft gating", intensity: 1 },
  { id: "aggressive", label: "Aggressive", textures: "clipped transients, distorted bass, tight compression", intensity: 5 },
  { id: "contemplative", label: "Contemplative", textures: "sparse arrangement, natural room tone, gentle fingerpicking", intensity: 1 },
  { id: "bittersweet", label: "Bittersweet", textures: "major-minor shifts, string swells, distant piano", intensity: 3 },
  { id: "energetic", label: "Energetic / Uplifting", textures: "driving rhythm, bright EQ, syncopated percussion", intensity: 4 },
];

export const INFLUENCES: Influence[] = [
  {
    id: "american-football",
    label: "American Football",
    sonic: "clean tapped guitars, trumpet accents, sprawling reverb, bittersweet melodies in odd time",
    genres: ["math-rock", "lofi"],
  },
  {
    id: "last-dinosaurs",
    label: "Last Dinosaurs",
    sonic: "jangly indie guitars, tight punchy drums, upbeat yet wistful vocals, clean production",
    genres: ["bedroom-pop", "dreampop"],
  },
  {
    id: "lush",
    label: "Lush",
    sonic: "dual layered guitars, ethereal female vocals, 4AD-style reverb, dreamy wall of sound",
    genres: ["shoegaze", "dreampop"],
  },
  {
    id: "hyde",
    label: "HYDE",
    sonic: "dramatic Japanese rock vocals, orchestral swells, gothic atmosphere, soaring melodies",
    genres: ["j-rock", "post-punk"],
  },
  {
    id: "oceanlabs",
    label: "OceanLab",
    sonic: "euphoric trance pads, angelic vocals, progressive builds, liquid basslines",
    genres: ["prog-house", "dreampop"],
  },
  {
    id: "snow-strippers",
    label: "Snow Strippers",
    sonic: "hyperpop glitch textures, pitch-shifted vocals, heavy sidechaining, ethereal chaos",
    genres: ["hyperpop", "bedroom-pop"],
  },
  {
    id: "kiri-monoral",
    label: "Monoral (Kiri)",
    sonic: "dark post-punk energy, brooding baritone, reverb-drenched guitars, cinematic tension",
    genres: ["post-punk", "j-rock"],
  },
  {
    id: "toe",
    label: "toe",
    sonic: "intricate polyrhythmic drums, clean guitar harmonics, dynamic builds, post-rock crescendos",
    genres: ["math-rock", "ambient"],
  },
  {
    id: "my-bloody-valentine",
    label: "My Bloody Valentine",
    sonic: "glide guitar, extreme pitch-bent tremolo bar, dense layered noise, whispered vocals buried in texture",
    genres: ["shoegaze"],
  },
  {
    id: "tycho",
    label: "Tycho",
    sonic: "warm analog synths, sunset-colored pads, downtempo groove, ambient guitar layers",
    genres: ["ambient", "lofi", "dreampop"],
  },
  {
    id: "deftones",
    label: "Deftones",
    sonic: "heavy-to-ethereal dynamics, shoegaze-metal layering, dreamy vocals over crushing riffs",
    genres: ["nu-metal", "shoegaze"],
  },
  {
    id: "bon-iver",
    label: "Bon Iver",
    sonic: "falsetto vocal layering, granular processed vocals, sparse folk into lush electronic builds",
    genres: ["indie-folk", "ambient"],
  },
  {
    id: "boards-of-canada",
    label: "Boards of Canada",
    sonic: "detuned analog synths, degraded tape loops, nostalgic lo-fi electronic textures",
    genres: ["ambient", "lofi"],
  },
  {
    id: "tricot",
    label: "tricot",
    sonic: "angular math-rock riffs, rapid time signature shifts, energetic female Japanese vocals, tight rhythm section",
    genres: ["math-rock", "j-rock"],
  },
];

export const TIME_SIGNATURES: string[] = [
  "4/4",
  "3/4",
  "5/4",
  "7/8",
  "6/8",
  "5/8",
  "11/8",
  "Mixed / Shifting",
];

export const CHORD_VOICINGS: ChordVoicing[] = [
  { id: "lydian", label: "Lydian (#4)", description: "Bright, floating, dreamlike quality" },
  { id: "phrygian-dom", label: "Phrygian Dominant", description: "Dark, Spanish/Middle-Eastern tension" },
  { id: "half-dim", label: "Half-Diminished", description: "Jazz melancholy, unresolved yearning" },
  { id: "sus4b9", label: "sus4(b9)", description: "Dissonant beauty, post-rock signature" },
  { id: "maj7sharp11", label: "maj7#11", description: "Luminous, open, Lydian sparkle" },
  { id: "min9", label: "min9", description: "Warm, moody, neo-soul color" },
  { id: "add9", label: "add9 / Open Voicings", description: "Jangly, spacious, indie shimmer" },
  { id: "dim7", label: "Diminished 7th", description: "Tense, cinematic, noir atmosphere" },
  { id: "dom7sharp9", label: "7#9 (Hendrix chord)", description: "Gritty, bluesy, psychedelic edge" },
];

export const TEXTURES: string[] = [
  "Fret slides",
  "Finger noise",
  "Timing drift",
  "Tape hiss",
  "Analog warmth",
  "Room mic bleed",
  "Vinyl crackle",
  "Tube saturation",
  "String buzz",
  "Pick scrapes",
  "Harmonic overtones",
  "Amp hum",
  "Pedal clicks",
  "Breath sounds",
  "Ghost notes",
  "Subtle vibrato wobble",
  "Bow noise",
  "Key clack",
  "Drum stick clicks",
  "Cable hum",
];

export const TEMPOS: Tempo[] = [
  { label: "Slow (60-80)", range: "60-80 BPM" },
  { label: "Chill (80-100)", range: "80-100 BPM" },
  { label: "Mid (100-120)", range: "100-120 BPM" },
  { label: "Upbeat (120-140)", range: "120-140 BPM" },
  { label: "Fast (140-170)", range: "140-170 BPM" },
  { label: "Very Fast (170+)", range: "170+ BPM" },
];
