import type { Preset } from "./types";

/**
 * One-click starting points. Every id here must exist in knowledge-base.ts —
 * `npm run build` type-checks the shape but not the ids, so keep them honest.
 */
export const PRESETS: Preset[] = [
  {
    id: "math-rock-study",
    label: "Calm Math Rock for Studying",
    tagline: "Tapped cleans in 7/8, brushed drums, nothing too loud",
    selection: {
      genreId: "math-rock",
      moodId: "focused",
      bpm: 88,
      instrumentIds: ["electric-guitar", "live-drums", "trumpet"],
      feel: { energy: 35, warmth: 70, complexity: 75 },
      influenceIds: ["toe", "american-football"],
      timeSignatureIds: ["7-8", "4-4"],
      chordVoicingIds: ["add9", "maj7sharp11"],
      textures: ["Fret slides", "Finger noise", "Tape hiss"],
      promptLength: "standard",
    },
  },
  {
    id: "shoegaze-walls",
    label: "Dark Shoegaze Walls",
    tagline: "Buried vocals, glide guitar, reverb you could get lost in",
    selection: {
      genreId: "shoegaze",
      moodId: "melancholy",
      bpm: 104,
      key: "e-minor",
      instrumentIds: ["electric-guitar", "bass", "live-drums", "vocals"],
      feel: { energy: 55, warmth: 60, complexity: 40 },
      influenceIds: ["my-bloody-valentine", "cocteau-twins"],
      timeSignatureIds: ["4-4"],
      chordVoicingIds: ["sus4b9"],
      textures: ["Amp hum", "Tape hiss", "Pitched vocal layers"],
      promptLength: "standard",
    },
  },
  {
    id: "lofi-late-night",
    label: "Late-Night Lo-Fi",
    tagline: "Dusty drums, Rhodes, rain against the window",
    selection: {
      genreId: "lofi",
      moodId: "nostalgic",
      bpm: 82,
      instrumentIds: ["drum-machine", "rhodes", "bass", "field-recordings"],
      feel: { energy: 30, warmth: 85, complexity: 30 },
      influenceIds: ["nujabes", "j-dilla"],
      timeSignatureIds: ["4-4"],
      chordVoicingIds: ["min9"],
      textures: ["Vinyl crackle", "Timing drift", "Rain / water ambience"],
      promptLength: "standard",
    },
  },
  {
    id: "dreampop-rain",
    label: "Rainy Window Dreampop",
    tagline: "Chorus-soaked guitars, breathy vocals, slow drift",
    selection: {
      genreId: "dreampop",
      moodId: "dreamy",
      bpm: 72,
      key: "a-major",
      instrumentIds: ["electric-guitar", "synth-pads", "vocals"],
      feel: { energy: 25, warmth: 70, complexity: 30 },
      influenceIds: ["cocteau-twins", "lush"],
      timeSignatureIds: ["4-4"],
      chordVoicingIds: ["maj9"],
      textures: ["Whispered doubles", "Rain / water ambience"],
      promptLength: "standard",
    },
  },
  {
    id: "neo-soul-golden",
    label: "Golden Hour Neo-Soul",
    tagline: "Warm pocket, min9 chords, finger snaps in the room",
    selection: {
      genreId: "rnb",
      moodId: "bittersweet",
      bpm: 86,
      key: "eb-major",
      instrumentIds: ["rhodes", "bass", "live-drums", "vocals"],
      feel: { energy: 45, warmth: 80, complexity: 55 },
      influenceIds: ["erykah-badu", "steve-lacy"],
      timeSignatureIds: ["4-4"],
      chordVoicingIds: ["min9", "dom9"],
      textures: ["Finger snaps", "Analog warmth", "Ghost notes"],
      promptLength: "standard",
    },
  },
  {
    id: "midwest-emo-twinkle",
    label: "Twinkly Midwest Emo",
    tagline: "Confessional, quiet-loud, trumpet in the bridge",
    selection: {
      genreId: "midwest-emo",
      moodId: "bittersweet",
      bpm: 112,
      instrumentIds: ["electric-guitar", "bass", "live-drums", "trumpet", "vocals"],
      feel: { energy: 60, warmth: 60, complexity: 65 },
      influenceIds: ["american-football"],
      timeSignatureIds: ["4-4", "6-8"],
      chordVoicingIds: ["add9"],
      textures: ["Fret slides", "Room mic bleed", "Falsetto cracks"],
      promptLength: "standard",
    },
  },
  {
    id: "synthwave-drive",
    label: "Neon Drive Synthwave",
    tagline: "Gated drums, arpeggiated bass, sunset chrome",
    selection: {
      genreId: "synthwave",
      moodId: "energetic",
      bpm: 124,
      key: "f-minor",
      instrumentIds: ["synth-lead", "synth-pads", "drum-machine", "bass"],
      feel: { energy: 75, warmth: 55, complexity: 35 },
      influenceIds: ["tame-impala"],
      timeSignatureIds: ["4-4"],
      chordVoicingIds: ["maj9"],
      textures: ["Sidechain pump", "Analog warmth", "Tape stop effect"],
      promptLength: "concise",
    },
  },
  {
    id: "prog-house-sunrise",
    label: "Sunrise Progressive House",
    tagline: "Slow-building layers, wide pads, one euphoric drop",
    selection: {
      genreId: "prog-house",
      moodId: "euphoric",
      bpm: 126,
      instrumentIds: ["synth-pads", "synth-lead", "drum-machine", "piano"],
      feel: { energy: 70, warmth: 55, complexity: 50 },
      influenceIds: ["oceanlabs"],
      timeSignatureIds: ["4-4"],
      chordVoicingIds: ["maj7sharp11"],
      textures: ["Sidechain pump", "Crowd murmur undertone"],
      promptLength: "detailed",
    },
  },
  {
    id: "cinematic-tension",
    label: "Cinematic Tension",
    tagline: "Ticking rhythm, brass swells, sub-bass dread",
    selection: {
      genreId: "classical-crossover",
      moodId: "anxious",
      bpm: 66,
      key: "d-minor",
      instrumentIds: ["strings", "piano", "808s"],
      feel: { energy: 40, warmth: 35, complexity: 60 },
      influenceIds: ["hans-zimmer"],
      timeSignatureIds: ["5-4"],
      chordVoicingIds: ["dim7"],
      textures: ["Bow noise", "Field recording layer"],
      promptLength: "detailed",
    },
  },
  {
    id: "liquid-dnb",
    label: "Liquid DnB Float",
    tagline: "Rolling breaks, sub weight, pitched vocal ghosts",
    selection: {
      genreId: "dnb",
      moodId: "dreamy",
      bpm: 174,
      instrumentIds: ["drum-machine", "bass", "synth-pads", "vocals"],
      feel: { energy: 80, warmth: 60, complexity: 55 },
      influenceIds: ["burial"],
      timeSignatureIds: ["4-4"],
      chordVoicingIds: ["min11"],
      textures: ["Pitched vocal layers", "Vinyl crackle", "Sample chop stutter"],
      promptLength: "standard",
    },
  },
];
